package util.Enums;

import java.util.EnumSet;
import java.util.Set;

public enum ErrorStatus {
    NO_ERROR,
    USERNAME_EXISTS,
    USERNAME_DOES_NOT_EXIST,
    USERCART_DOES_NOT_EXISTS,
    MEMBMER_ALREADY_HAS_ROLE,
    MEMBMER_ALREADY_HAS_CONTRACT,
    MEMBER_ROLE_NOT_EXISTS,
    PRIMARY_ADDRESS_DOES_NOT_EXISTS,
    ADDRESS_DOES_NOT_EXISTS,
    INVALID_USERNAME,
    INVALID_PASSWORD,
    INVALID_EMAIL,
    INVALID_PHONE_NUMBER,
    SESSION_ID_DOES_NOT_EXIST,
    GUEST_SESSION,
    ALREADY_LOGGED_IN,
    NOT_LOGGED_IN,
    USERNAME_PASSWORD_MISMATCH,
    STORE_DOES_NOT_EXIST,
    PRODUCT_DOES_NOT_EXIST,
    DISCOUNT_DOES_NOT_EXIST,
    TRANSACTION_DOES_NOT_EXIST,
    INVALID_STORE_NAME,
    INVALID_STORE_DESCRIPTION,
    INVALID_PRODUCT_NAME,
    INVALID_PRODUCT_PRICE,
    INVALID_PRODUCT_QUANTITY,
    INVALID_PRODUCT_CATEGORY,
    NEGATIVE_QUANTITY,
    STORE_EXISTS,
    PRODUCT_EXISTS,
    NO_PERMISSION_ADD_OR_REMOVE_STORE_OWNER,
    NO_PERMISSION_ADD_OR_REMOVE_STORE_MANAGER,
    NO_PERMISSION_MAKE_STORE_INACTIVE,
    NO_PERMISSION_STORAGE_MANAGEMENT,
    NO_PERMISSION_CHANGE_STORE_POLICY,
    NO_PERMISSION_CHANGE_OWNER_PERMISSIONS,
    NO_PERMISSION_GET_EMPLOYEES_DATA,
    NO_PERMISSION_GET_PURCHASE_HISTORY,
    NO_MANAGER_PERMISSION,
    NO_PERMISSION_REPLY_TO_MESSAGES,
    NO_PERMISSION_TO_APPOINT,
    NO_PERMISSION,
    OFFER_NOT_FULLY_CONSENTED,
    PAYMENT_PROCESS_FAILED,
    INVALID_STORE_FOUNDER,
    PURCHASE_LIMITATION,
    EMPTY_COLLECTION,
    MAX,
    OFFER_DOES_NOT_EXIST,

    CONTRACT_DOES_NOT_EXIST,
    INVALID_PERCENTAGE;

    public static final Set<ErrorStatus> DATA_ERROR_STATUSES =
            EnumSet.of(INVALID_USERNAME, INVALID_PASSWORD, INVALID_EMAIL, INVALID_PHONE_NUMBER, INVALID_STORE_NAME,
                    INVALID_STORE_DESCRIPTION, INVALID_PRODUCT_NAME, INVALID_PRODUCT_PRICE, INVALID_PRODUCT_QUANTITY,
                    INVALID_PRODUCT_CATEGORY, NEGATIVE_QUANTITY, INVALID_PERCENTAGE, EMPTY_COLLECTION);

    public static final Set<ErrorStatus> NON_EXISTENT_DATA_ERROR_STATUSES =
            EnumSet.of(STORE_DOES_NOT_EXIST, USERNAME_DOES_NOT_EXIST, USERCART_DOES_NOT_EXISTS, MEMBER_ROLE_NOT_EXISTS,
                    INVALID_STORE_FOUNDER, PRIMARY_ADDRESS_DOES_NOT_EXISTS, ADDRESS_DOES_NOT_EXISTS, PRODUCT_DOES_NOT_EXIST,
                    DISCOUNT_DOES_NOT_EXIST, OFFER_DOES_NOT_EXIST, CONTRACT_DOES_NOT_EXIST, TRANSACTION_DOES_NOT_EXIST);

    public static final Set<ErrorStatus> EXISTENT_DATA_ERROR_STATUSES =
            EnumSet.of(USERNAME_EXISTS, MEMBMER_ALREADY_HAS_ROLE, STORE_EXISTS, PRODUCT_EXISTS, MEMBMER_ALREADY_HAS_CONTRACT);

    public static final Set<ErrorStatus> SESSION_ERROR_STATUSES =
            EnumSet.of(ALREADY_LOGGED_IN, SESSION_ID_DOES_NOT_EXIST, NOT_LOGGED_IN, GUEST_SESSION,
                    USERNAME_PASSWORD_MISMATCH);

    public static final Set<ErrorStatus> PERMISSION_ERROR_STATUSES =
            EnumSet.of(NO_PERMISSION, NO_PERMISSION_ADD_OR_REMOVE_STORE_MANAGER, NO_PERMISSION_ADD_OR_REMOVE_STORE_OWNER,
                    NO_PERMISSION_MAKE_STORE_INACTIVE, NO_PERMISSION_CHANGE_OWNER_PERMISSIONS,
                    NO_PERMISSION_GET_EMPLOYEES_DATA, NO_PERMISSION_STORAGE_MANAGEMENT,
                    NO_PERMISSION_CHANGE_STORE_POLICY, NO_PERMISSION_GET_PURCHASE_HISTORY,
                    NO_PERMISSION_REPLY_TO_MESSAGES, NO_MANAGER_PERMISSION, NO_PERMISSION_TO_APPOINT);

    public static final Set<ErrorStatus> PURCHASE_ERROR_STATUSES =
            EnumSet.of(OFFER_NOT_FULLY_CONSENTED, PAYMENT_PROCESS_FAILED, PURCHASE_LIMITATION);
}
